# Generated by Django 5.1.6 on 2025-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdata', '0002_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='fee_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
