# Generated by Django 5.1.6 on 2025-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_card',
            field=models.FileField(blank=True, null=True, upload_to='membership_cards/'),
        ),
    ]
