# Generated by Django 5.1.6 on 2025-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_customuser_membership_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_card_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
