# Generated by Django 5.1.6 on 2025-04-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_customuser_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=10)),
                ('otp_expiry', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('otp_tries', models.IntegerField(default=0)),
            ],
        ),
    ]
