# Generated by Django 5.1.6 on 2025-05-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_remove_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], help_text='Select your blood group', max_length=3, null=True),
        ),
    ]
