# Generated by Django 5.1.6 on 2025-08-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
