# Generated by Django 5.1.6 on 2025-08-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0014_customuser_college_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KEASequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='kea_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
