# Generated by Django 5.1.6 on 2025-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0015_keasequence_customuser_kea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
