# Generated by Django 5.1.6 on 2025-08-24 05:05

import userdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0016_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership_card',
            field=models.FileField(blank=True, help_text='Upload membership card PDF or image', null=True, upload_to=userdata.models.membership_card_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload profile picture (max 5MB)', null=True, upload_to=userdata.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Generated QR code for membership', null=True, upload_to=userdata.models.qr_code_path),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='userdata_customuser',
        ),
        migrations.AlterModelTable(
            name='keasequence',
            table='kea_sequence',
        ),
    ]
